{% set version = "3.2.0" %}

package:
  name: pydap
  version: {{ version }}

source:
  fn: Pydap-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/Pydap/Pydap-{{ version }}.tar.gz
  sha256: 86dca669f84eecba6ff67af7fa3332af24a0163a72991d02452f4ca1f4d3f99f
  patches:
    - gunicorn.patch
    - charset.patch

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - singledispatch
    - webob
    - jinja2
    - docopt
    - six >=1.4.0
    - mechanicalsoup
    # Optional.
    - gsw
    - scipy
    - requests
    #- coards
    # Server only.
    - gunicorn  # [not win]

test:
  imports:
    - pydap

about:
  home: http://pydap.org/
  license: MIT
  license_file: docs/license.rst
  summary: 'Pure Python Opendap/DODS client and server.'

extra:
  recipe-maintainers:
    - ocefpaf
