# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ODmNwdMU2qNUk7ADcALzyUUl3JKQLJK7Q0t9T/h/Mz9/uDE7kWic4AgYISBKCEHUI5XXGoK5+30Y5uosT0KvR2rAiC7pUmwFZkIFGoRcxAGqB2HXZF7C0eXd6OSC0wxiHX9I8KHaRq7LU5oeUrb1O524M2bh7qMK887rj9F6IrN01aE28FJMePBkZ+xLDZYunmWVB3K7PWaY/MkyEjl+9I6d9xeoqwKfToODqHgJ3x3KdGJz27s4/xxys1DOg4gfOQu3S5uznuo6k68+bIf6SYM0KTLKIquqpOQfFUNHesbeE8R+cliwD27t9fiQ01YxlMXGKQ50PUnft88ZD+uRl49ZQGDVuzuYYP7XC+rWRm2UsZ/8AEJE8VS5BvnUiSon7w2kWwousJVsjqLb/unnXTSBsX2wUaJZcoO40hXKb/+7L4IY/YfIi+lIlMLWdApURZdfU2bh9kUxr0EUdF4Xa7w+HYXfqq0nQIFZDRiEYwflzbCNQ+puqkv6CY0puOK39QpRzmpKa72P9Zwt1RssxL6L0hbSEPllRF7hkJJfwPBXMbJkOW95bQsRUO37+DTblrPW13LvM0VFuImfc242icJjv3GvcJ/WLaJGbn8FdKDJU2m3WA5tG4eKDEKjM9bcoYmEBf+2FojoHTpbqXflktj8MlB6votgGxJFHoozvQk="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
