travis:
  secure:
    BINSTAR_TOKEN: ODmNwdMU2qNUk7ADcALzyUUl3JKQLJK7Q0t9T/h/Mz9/uDE7kWic4AgYISBKCEHUI5XXGoK5+30Y5uosT0KvR2rAiC7pUmwFZkIFGoRcxAGqB2HXZF7C0eXd6OSC0wxiHX9I8KHaRq7LU5oeUrb1O524M2bh7qMK887rj9F6IrN01aE28FJMePBkZ+xLDZYunmWVB3K7PWaY/MkyEjl+9I6d9xeoqwKfToODqHgJ3x3KdGJz27s4/xxys1DOg4gfOQu3S5uznuo6k68+bIf6SYM0KTLKIquqpOQfFUNHesbeE8R+cliwD27t9fiQ01YxlMXGKQ50PUnft88ZD+uRl49ZQGDVuzuYYP7XC+rWRm2UsZ/8AEJE8VS5BvnUiSon7w2kWwousJVsjqLb/unnXTSBsX2wUaJZcoO40hXKb/+7L4IY/YfIi+lIlMLWdApURZdfU2bh9kUxr0EUdF4Xa7w+HYXfqq0nQIFZDRiEYwflzbCNQ+puqkv6CY0puOK39QpRzmpKa72P9Zwt1RssxL6L0hbSEPllRF7hkJJfwPBXMbJkOW95bQsRUO37+DTblrPW13LvM0VFuImfc242icJjv3GvcJ/WLaJGbn8FdKDJU2m3WA5tG4eKDEKjM9bcoYmEBf+2FojoHTpbqXflktj8MlB6votgGxJFHoozvQk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
