travis:
  secure:
    BINSTAR_TOKEN: FDrnMJc5eLxb+LBmw98/ZRK4Y2BixFo5trifn8h/zOYw9McYXY97hjdsjkSzPilU244X3jXeLvjl+REMppgdupmOYziSu62/dzy9KDSMPv7Y1iCtnK+FsYBmhKvZuCP8K5Sj+hwjVXVt2/FKU3TX5sPDwdGXrwxwrONQuKhvOcePVSleva41gTb6h0xVlZy9rMDM15h+oIl+AZliOfCp+mZ0Q09uFuKn0n2Sx/d328ls/V7TuaLTKHEm3nbVmrSzcN6a/7yixOuNzUQQ1FQPb10JO4/ZevWyt3fkD5w7Bvh8PtN4v0I5XQojOWDZhmf/fDfXZwvO3X4J1Vx4dx+ywGZ6rJZk+DYybDX6Zp2yo6evWOpvKKF1go2u972MrxC/VmfUdfp7R0WfkbsDWUALDl3H0FRIuUL4ssvdzDOYyCRC2kolEC9RGPCCU2av/x+pBvYf30IO4jLB042IfvPZRFFQaclW5u2gTqoVs3UdB9e9yMl3gqWjMb/4b9K3Q8spmW+uuOvzXnEQW4Nd6fdNbuHqY5/yq0ZRneDj3LiDoLXSQAuVNYIfOGOMhC9ap81vLqpim6zIwiYuYObNfVq+D/co1CaYWqCW6GAaOKOgZlW243i0yBai9hvdhntqC8UexZL0jtu2n7ODbpFi5irllToWYE6dvUVOEeJfLHI/2n8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
